/// oAirVentSmall — Create

depth = -15000;

sprite_index = spriteAirVentSmall;

// ====================================================
// EDITOR VARIABLES
// ====================================================

if (!variable_instance_exists(id, "enabled"))
{
    enabled = true;
}

// ----------------------------------------------------
// Updraft strength
//
// 1  = very gentle
// 10 = standard strong vent
// 20 = powerful
// 30 = extremely powerful
// ----------------------------------------------------
if (!variable_instance_exists(id, "strength_level"))
{
    strength_level = 10;
}

// Number of repeated wind sprites above the vent.
if (!variable_instance_exists(id, "wind_tiles"))
{
    wind_tiles = 4;
}

// Horizontal direction imposed by the vent.
//
// -1 = left
//  0 = straight upward
//  1 = right
// ----------------------------------------------------
if (!variable_instance_exists(id, "horizontal_bias"))
{
    horizontal_bias = 0;
}

// Maximum sideways speed generated by the bias.
if (!variable_instance_exists(id, "bias_max_speed"))
{
    bias_max_speed = 1.25;
}

// How quickly the vent takes control of downward-moving players.
if (!variable_instance_exists(id, "capture_strength"))
{
    capture_strength = 1;
}

// ====================================================
// VALUE SAFETY
// ====================================================

strength_level = clamp(round(strength_level), 1, 30);
wind_tiles = max(1, round(wind_tiles));
horizontal_bias = clamp(horizontal_bias, -1, 1);
bias_max_speed = max(0, bias_max_speed);
capture_strength = max(0, capture_strength);

// ====================================================
// WIND SPRITE
// ====================================================

wind_sprite = asset_get_index("spriteAirVentWind");

// ====================================================
// ANIMATION
// ====================================================

fan_animation_speed  = 0.28;
wind_animation_speed = 0.22;

image_index = 0;
image_speed = fan_animation_speed;

wind_animation_position = 0;

// ====================================================
// WIND COLUMN
// ====================================================

// Slight visual overlap between repeated wind sprites.
wind_tile_gap = -2;

// Width of active airflow compared with wind sprite width.
wind_collision_width_scale = 0.78;

// ====================================================
// STRENGTH CALCULATION
// ====================================================

var strength_amount = (strength_level - 1) / 29;

updraft_acceleration = lerp(0.35, 1.80, strength_amount);
maximum_rise_speed   = lerp(3.0, 12.0, strength_amount);
capture_rise_speed   = lerp(1.5, 5.5, strength_amount);
horizontal_acceleration = lerp(0.06, 0.22, strength_amount);

// ====================================================
// LOOPING DIRECTIONAL AUDIO
// ====================================================

snd_air_vent_small_loop = asset_get_index("AirVentSmallLoop1");

air_vent_loop_instance = noone;
air_vent_audio_emitter = audio_emitter_create();

air_vent_loop_gain  = 0.32;
air_vent_loop_pitch = 1.0;

air_vent_loop_inner_dist = 100;
air_vent_loop_outer_dist = 380;

// Only this many closest small vents may play.
air_vent_loop_max_voices = 3;

// Controls stereo position strength.
// 1 gives a clear but not extreme left/right effect.
air_vent_pan_strength = 1.0;

// ====================================================
// DEBUG
// ====================================================

debug_draw = false;