/// oAirVentSmall — Create

depth = -15000;

sprite_index = spriteAirVentSmall;


// ====================================================
// EDITOR VARIABLES
// ====================================================

if (!variable_instance_exists(id, "enabled"))
{
    enabled = true;
}


// ----------------------------------------------------
// Updraft strength
//
// 1  = very gentle
// 10 = standard strong vent
// 20 = powerful
// 30 = extremely powerful
// ----------------------------------------------------
if (!variable_instance_exists(id, "strength_level"))
{
    strength_level = 10;
}


// Number of repeated wind sprites above the vent.
if (!variable_instance_exists(id, "wind_tiles"))
{
    wind_tiles = 4;
}


// Horizontal direction imposed by the vent.
//
// -1 = left
//  0 = straight upward
//  1 = right
//
// Decimal values are supported.
// ----------------------------------------------------
if (!variable_instance_exists(id, "horizontal_bias"))
{
    horizontal_bias = 0;
}


// Maximum sideways speed generated by the bias.
if (!variable_instance_exists(id, "bias_max_speed"))
{
    bias_max_speed = 1.25;
}


// How quickly the vent takes control of downward-moving
// players.
//
// Higher values cancel falling momentum more quickly.
// ----------------------------------------------------
if (!variable_instance_exists(id, "capture_strength"))
{
    capture_strength = 1;
}


// ====================================================
// VALUE SAFETY
// ====================================================

strength_level =
    clamp(
        round(strength_level),
        1,
        30
    );

wind_tiles =
    max(
        1,
        round(wind_tiles)
    );

horizontal_bias =
    clamp(
        horizontal_bias,
        -1,
        1
    );

bias_max_speed =
    max(
        0,
        bias_max_speed
    );

capture_strength =
    max(
        0,
        capture_strength
    );


// ====================================================
// WIND SPRITE
// ====================================================

wind_sprite =
    asset_get_index("spriteAirVentWind");


// ====================================================
// ANIMATION
// ====================================================

fan_animation_speed  = 0.28;
wind_animation_speed = 0.32;

image_index = 0;
image_speed = fan_animation_speed;

wind_animation_position = 0;


// ====================================================
// WIND COLUMN
// ====================================================

// Slight visual overlap between repeated wind sprites.
wind_tile_gap = -2;

// Width of the actual active airflow compared with the
// complete wind sprite width.
wind_collision_width_scale = 0.78;


// ====================================================
// STRENGTH CALCULATION
// ====================================================

// Convert strength_level 1–30 into a value from 0–1.
var strength_amount =
    (strength_level - 1) / 29;


// Constant upward acceleration.
//
// This is deliberately much stronger than player
// gravity, even at moderate settings.
updraft_acceleration =
    lerp(
        0.35,
        1.80,
        strength_amount
    );


// Maximum upward speed maintained by the vent.
maximum_rise_speed =
    lerp(
        3.0,
        12.0,
        strength_amount
    );


// Minimum upward speed given shortly after entering.
//
// This prevents the player merely hovering when they
// enter while falling quickly.
capture_rise_speed =
    lerp(
        1.5,
        5.5,
        strength_amount
    );


// Horizontal bias acceleration.
horizontal_acceleration =
    lerp(
        0.06,
        0.22,
        strength_amount
    );


// ====================================================
// DEBUG
// ====================================================

debug_draw = false;